spring:
  profiles:
    include: datasource,redis
  security:
    user:
      name: frank
      password: aa000000
eureka:
  client:
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:8011/eureka/
mq:
  host: 192.168.1.102
  port: 5672
  userName: qq
  password: 1234
  virtualHost: /qq

