server:
  contextPath: /
spring:
  datasource:
    druid:
      filters: config,stat,wall
      connection-properties: config.file=http://35.185.158.204/druid-pool.properties;config.decrypt=true
  redis:
    host: redis
    port: 6379
    #password: redis
    pool:
      max-active: 20
      max-wait: -1
      max-idle: 5
      min-idle: 0
    timeout: 10000
  freemarker:
    allow-request-override: false
    allow-session-override: false
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    enabled: true
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: true
    prefer-file-system-access: true
    suffix: .ftl
    template-loader-path: classpath:/templates/
    settings.template_update_delay: 0
    settings.default_encoding: UTF-8
    settings.classic_compatible: true
    settings.date_format: yyyy-MM-dd
    settings.time_format: HH:mm:ss
    settings.datetime_format: yyyy-MM-dd HH:mm:ss
  http:
    multipart.enabled: true
    multipart.max-file-size: 10MB
    multipart.max-request-size: 10MB
  mail:
    host: smtp.sina.com
    username: allanpoecn@sina.com
    password: 5151229
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true