server:
  port: 8021
spring:
  redis:
    host: 47.92.159.62
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0
    timeout: 10000
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  security:
    user:
      name: frank
      password: aa000000
eureka:
  instance:
    metadata-map:
      version: 0.0.1-SNAPSHOT
  client:
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:8011/eureka/
