spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 20
        max-wait: 5000
        max-idle: 5
        min-idle: 0
    timeout: 10000
