server:
  port: 8023
spring:
  profiles:
    include: datasource,redis
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  security:
    user:
      name: frank
      password: aa000000
eureka:
  instance:
    metadata-map:
      version: 0.0.1-SNAPSHOT
  client:
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:8011/eureka/
grpc:
  server:
    port: 0
springfox:
  documentation:
    swagger:
      v2:
        host: /manage/v2/api-docs
